# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29f381ed6cb5e88415210b37b6b05177578b93ae4ea00549ce2b104206ecf0a97e452988ebfd7a500aef53e8e6aba65b31ae9e572f98ec7c7c894f1d65e97395

test:
  secret_key_base: a235079c4ff1a8262aee5f60ad808628c01952ececb882a64208c89f59340f2cc16a930b6597f34a92e95570648320e818c86f7b6581c88f9623694315521ea7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
